name: recette
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  url_launcher: ^6.3.0
  printing: ^5.12.0
  pdf: ^3.10.8
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  share_plus: ^11.0.0
  receive_sharing_intent:
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent
      ref: 2cea396843cd3ab1b5ec4334be4233864637874e
  crypto: ^3.0.3
  file_picker: ^10.2.3
  english_words: ^4.0.0
  provider: ^6.1.5
  firebase_core: ^4.0.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
  # Declare the fonts so the app can use them.
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
          style: italic
          weight: 700